@props([
    'title' => '',
    'period' => '',
    'branch' => 'All Branches',
    'filters' => [], // ['label' => '', 'value' => '']
    'generatedBy' => null,
])
<x-document.meta :cols="max(2, min(4, count($filters) + 2))" :items="array_merge(
    [['label' => 'Report Period', 'value' => $period], ['label' => 'Branch', 'value' => $branch]],
    $filters,
    [
        ['label' => 'Generated', 'value' => now()->format('d M Y H:i')],
        ['label' => 'Generated By', 'value' => $generatedBy ?? auth()->user()?->name],
    ],
)" />
