<div class="space-y-5">
    <div class="flex items-center justify-between">
        <h2 class="text-xl font-bold text-gray-900">Payroll Runs</h2>
        <div class="flex gap-2">
            <a href="{{ route('payroll.index') }}" wire:navigate class="btn-secondary btn-sm">← Dashboard</a>
            @can('payroll.generate')
                <a href="{{ route('payroll.generate') }}" wire:navigate class="btn-primary">+ Generate</a>
            @endcan
        </div>
    </div>

    {{-- Filters --}}
    <div class="flex flex-wrap items-center gap-3">
        <input wire:model.live="yearMonth" type="month" class="input text-sm w-auto">
        <div class="flex flex-wrap gap-1">
            <button wire:click="$set('status', '')"
                class="px-2.5 py-1.5 rounded-lg text-xs font-medium transition-colors
                    {{ $status === '' ? 'bg-indigo-600 text-white' : 'bg-white text-gray-600 border border-gray-200' }}">
                All
            </button>
            @foreach ($this->statuses as $s)
                <button wire:click="$set('status', '{{ $s->value }}')"
                    class="px-2.5 py-1.5 rounded-lg text-xs font-medium transition-colors
                        {{ $status === $s->value ? 'bg-indigo-600 text-white' : 'bg-white text-gray-600 border border-gray-200' }}">
                    {{ $s->label() }}
                </button>
            @endforeach
        </div>
    </div>

    {{-- Run Table --}}
    <div class="card overflow-hidden">
        <div class="overflow-x-auto">
            <table class="w-full">
                <thead class="bg-gray-50 border-b border-gray-200">
                    <tr>
                        <th class="table-th">Run Number</th>
                        <th class="table-th">Period</th>
                        <th class="table-th">Scope</th>
                        <th class="table-th text-right">Employees</th>
                        <th class="table-th text-right">Gross</th>
                        <th class="table-th text-right">Net Payable</th>
                        <th class="table-th text-right">Paid</th>
                        <th class="table-th">Status</th>
                        <th class="table-th">Generated By</th>
                        <th class="table-th">Actions</th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-gray-100">
                    @forelse($this->runs as $run)
                        <tr class="hover:bg-gray-50" wire:key="run-{{ $run->id }}">
                            <td class="table-td">
                                <a href="{{ route('payroll.run.show', $run) }}" wire:navigate
                                    class="font-mono font-bold text-indigo-600 hover:underline text-sm">
                                    {{ $run->run_number }}
                                </a>
                            </td>
                            <td class="table-td font-medium text-gray-900">
                                {{ $run->monthName() }}
                            </td>
                            <td class="table-td text-xs text-gray-500">
                                {{ $run->branch?->name ?? 'All Branches' }}
                                @if ($run->department)
                                    / {{ $run->department->name }}
                                @endif
                                @if ($run->employment_type)
                                    <div class="text-gray-400">
                                        {{ ucfirst(str_replace('_', ' ', $run->employment_type)) }}</div>
                                @endif
                            </td>
                            <td class="table-td text-right">{{ $run->total_employees }}</td>
                            <td class="table-td text-right text-gray-600">
                                ৳{{ number_format($run->total_gross_earnings, 0) }}
                            </td>
                            <td class="table-td text-right font-bold text-gray-900">
                                ৳{{ number_format($run->total_net_payable, 0) }}
                            </td>
                            <td class="table-td text-right">
                                <span
                                    class="{{ (float) $run->total_paid > 0 ? 'text-green-600 font-semibold' : 'text-gray-300' }}">
                                    {{ (float) $run->total_paid > 0 ? '৳' . number_format($run->total_paid, 0) : '—' }}
                                </span>
                            </td>
                            <td class="table-td">
                                <span class="badge {{ $run->status->badgeClass() }} text-xs">
                                    {{ $run->status->label() }}
                                </span>
                            </td>
                            <td class="table-td text-xs text-gray-400">
                                {{ $run->generatedBy?->name }}
                                <div>{{ $run->created_at->format('d M Y') }}</div>
                            </td>
                            <td class="table-td">
                                <div class="flex items-center gap-2">
                                    <a href="{{ route('payroll.run.show', $run) }}" wire:navigate
                                        class="text-xs text-indigo-600 hover:underline font-medium">
                                        View
                                    </a>
                                    @if ($run->status->value === 'under_review')
                                        @can('payroll.approve')
                                            <button wire:click="quickApprove({{ $run->id }})"
                                                wire:confirm="Approve {{ $run->run_number }} and post journal?"
                                                class="text-xs text-green-600 hover:underline font-medium">
                                                Approve
                                            </button>
                                        @endcan
                                    @endif
                                    @if ($run->status->canBeCancelled())
                                        <button wire:click="openCancelModal({{ $run->id }})"
                                            class="text-xs text-red-400 hover:underline font-medium">
                                            Cancel
                                        </button>
                                    @endif
                                </div>
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="10" class="table-td text-center text-gray-400 py-10">
                                No payroll runs for the selected period.
                            </td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
        @if ($this->runs->hasPages())
            <div class="px-4 py-3 border-t border-gray-100">{{ $this->runs->links() }}</div>
        @endif
    </div>

    {{-- Cancel Modal --}}
    @if ($showCancelModal)
        <div class="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4">
            <div class="bg-white rounded-2xl shadow-2xl max-w-md w-full p-6 space-y-4">
                <h3 class="font-bold text-gray-900">Cancel Payroll Run</h3>
                <p class="text-sm text-gray-500">
                    No journal entries have been posted for Draft/Under Review runs.
                    This action cannot be undone.
                </p>
                <div>
                    <label class="label">Reason *</label>
                    <textarea wire:model="cancelReason" rows="3" class="input"
                        placeholder="Explain why this run is being cancelled…"></textarea>
                    @error('cancelReason')
                        <p class="error">{{ $message }}</p>
                    @enderror
                </div>
                <div class="flex gap-3">
                    <button wire:click="cancel" class="btn-danger flex-1" wire:loading.attr="disabled"
                        wire:target="cancel">
                        <span wire:loading.remove>Cancel Run</span>
                        <span wire:loading>Processing…</span>
                    </button>
                    <button wire:click="$set('showCancelModal', false)" class="btn-secondary">Back</button>
                </div>
            </div>
        </div>
    @endif
</div>
